### ISSUE TITLE
温度获取一直是0

### ISSUE THREAD

**Issue by Rookie9512** [dscao/openwrt#1]
温度获取一直是0,需要改cpuinfo改成自己温度对应的id吗

**Comment by dscao** [comment]
openwrt版本不同，这个数据格式会有差异。另外如果是虚拟机安装的本身就没有温度，都会显示为0。
如果是物理机安装的，可以对照自己openwrt概览页面中的CPU温度信息，调试查看json数据，自己修改一下。
