### ISSUE TITLE
Home Assistant 2023.8.3 提示安装失败

### ISSUE THREAD

**Issue by swzsweet** [dscao/openwrt#4]
Home Assistant 2023.8.3
![image](https://github.com/dscao/openwrt/assets/11248150/503030cb-2563-448e-8acd-892ccdecb6d6)

Logger: custom_components.openwrt
Source: helpers/update_coordinator.py:262
Integration: openwrt ([documentation](https://github.com/dscao/openwrt))
First occurred: 17:48:23 (4 occurrences)
Last logged: 17:49:00

Error fetching openwrt data: Passing coroutines is forbidden, use tasks explicitly.

**Comment by dscao** [comment]
最新版本应该支持了
