### ISSUE TITLE
提示安装失败

### ISSUE THREAD

**Issue by XZWJ010** [dscao/openwrt#6]
大佬，安装您的集成提示安装失败，是不能用了吗？
下面是现在系统的版本
[
![截图 2024-06-28 20-37-47](https://github.com/dscao/openwrt/assets/172097844/5781ee61-15de-40d5-b86c-55b5fcc3f0b0)
](url)
![24-06-26 15-01-22 3447](https://github.com/dscao/openwrt/assets/172097844/8684e5b6-11d0-432c-91ed-03c1403f71d6)

**Comment by dscao** [comment]
新版本的试试。兼容openwrt的两种主流版本格式了。
